version: "2" # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 10
  file-lines:
    enabled: true
    config:
      threshold: 1000
