commitizen:
  changelog_file: CHANGELOG.md
  tag_format: v_$major.$minor.$patch$prerelease
  update_changelog_on_bump: false
  version: 2.2.0
  version_files:
  - setup.py:version
  - sepal_ui/__init__.py:__version__
