name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  PLANET_API_CREDENTIALS: ${{ secrets.PLANET_API_CREDENTIALS }}
  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        include:
          - os: macos-latest # macos test
            python-version: "3.10"
          - os: windows-latest # windows test
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: python -m pip install nox
      - name: test with pytest
        run: nox -s test
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: assess dead fixtures
        if: matrix.python-version == '3.10'
        run: nox -s dead-fixtures
